# Generated by Django 5.1.6 on 2025-03-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('college', models.CharField(max_length=80)),
                ('depart', models.CharField(max_length=30)),
                ('passed', models.IntegerField()),
                ('domain', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=15)),
                ('status', models.BooleanField()),
                ('call_res', models.CharField(max_length=20)),
            ],
        ),
    ]
