# Generated by Django 5.1.6 on 2025-03-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_apply_form_call_res_alter_apply_form_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
